spring.application.name=quickdrop
server.port = 8080

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/quickdrop_db
spring.datasource.username=postgres
spring.datasource.password=21283


# Hibernate Setting - update automatically based on entity changes 
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements - useful for debugging
spring.jpa.show-sql=true

spring.profiles.include=secret
